### ISSUE TITLE
Unable to locate package ros-galactic-slam-toolbox

### ISSUE THREAD

**Issue by trunc8** [SteveMacenski/nav2_rosdevday_2021#5]
System Description:  
- OS: Ubuntu 20.04
- Environment: ROS2 Galactic inside a Docker environment

1. On running `rosdep install --from-path src --ignore-src -r -y`, the following error occurs-
```
executing command [sudo -H apt-get install -y ros-galactic-slam-toolbox]
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package ros-galactic-slam-toolbox
ERROR: the following rosdeps failed to install
  apt: command [sudo -H apt-get install -y ros-galactic-slam-toolbox] failed
  apt: Failed to detect successful installation of [ros-galactic-slam-toolbox]
```
2. I could, still, successfully simulate Nav2 Goal, Nav Through Poses, and Waypoint Following in the amazon warehouse world as well as the security demo. The costmaps did not appear in RViz, accompanied by this warning:  
![image](https://user-images.githubusercontent.com/50488330/122289942-e0a0e800-cf10-11eb-96e9-374d52917337.png)  
I suspect this may be related to missing installation of the slam toolbox.

3. The _Time Taken_ indicator in the Nav2 RViz Panel did not update, while the other indicators worked flawlessly.

**Comment by SteveMacenski** [comment]
Its because there hasn't been a sync yet with galactic for you to access the binaries. You can easily just clone it and build in the workspace if you want it, but its not used in any of these demos so you don't need to worry about it. 

I don't see the costmaps in the construct's platform but I see it in my local builds (though I haven't tested on galactic binaries, maybe a QOS setting changed?)
